# Generated by Django 4.2 on 2023-04-09 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_question_authorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='authorId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='website.user'),
        ),
    ]
