# Generated by Django 4.2 on 2023-04-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_question_upvoteanswer_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downvoteanswer',
            old_name='question',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='upvotequestion',
            old_name='answer',
            new_name='question',
        ),
    ]
