# Generated by Django 4.2 on 2023-04-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_question_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
