# Generated by Django 4.2 on 2023-04-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_question_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='isRight',
            field=models.BooleanField(default=False),
        ),
    ]
