# Generated by Django 4.2.1 on 2023-05-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_question_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_ava.jpg', null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
